apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o kubefiles/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: db-backend
  name: db-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o kubefiles/
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: db-backend
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: REDIS_AOF_ENABLED
              value: "no"
          image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
          name: redisdb
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
