---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis
    tier: backend
  name: db-backend
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
volumeMode: Filesystem
